api_keys = []

[[accounts]]
email = "debatefeatgdcdve+mclendon@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "t.a.ya.hs.c.h.war.z2.5.7@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "vsigsiehvdidod+hewitt@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "sks.j.hsms.h.sms.n.bv@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "slsnvskshevvekeb+berg@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "v.s.i.gs.i.ehv.di.d.o.d@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "slsnvskshevvekeb+christie@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "wa.sh.brom.a.i.1.9.1@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[deepseek]
api_base = "https://chat.deepseek.com/api/v0"
wasm_url = "https://fe-static.deepseek.com/chat/static/sha3_wasm_bg.7b9ca65ddd.wasm"
user_agent = "DeepSeek/2.0.4 Android/35"
client_version = "2.1.0"
client_platform = "android"
client_locale = "zh_CN"
model_types = [
    "default",
    "expert",
    "vision",
]
max_input_tokens = [
    1048576,
    1048576,
    1048576,
]
max_output_tokens = [
    384000,
    384000,
    384000,
]
model_aliases = []

[deepseek.tool_call]
extra_starts = [
    "<|tool_call_begin|>",
    "<tool_calls>",
    "<tool_call>",
]
extra_ends = [
    "<|tool_call_end|>",
    "</tool_calls>",
    "</tool_call>",
]

[server]
host = "127.0.0.1"
port = 22217
cors_origins = ["http://localhost:22217"]

[proxy]

[admin]
password_hash = "$2b$12$SKq2TSFB8WGSUEjAl1fmSuai9TDAfMU53DEHk8bNKZFqqYTXKqt5q"
jwt_secret = "19fc9c75863e029df11e4fc993673d75542910bb9c513b8270bc2b2ccc855db7"
jwt_issued_at = 1778648095
